apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vetautet-app-hpa
  namespace: vetautet
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vetautet-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60    # scale up when avg CPU > 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70    # scale up when avg memory > 70%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60         # add up to 2 pods per minute
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60         # remove 1 pod per minute
