apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vetautet
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Vetautet ticket booking system
  sourceRepos:
    - '*'   # replace with your actual git repo URL
  destinations:
    - namespace: vetautet
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
